#ifndef PIN_H
#define PIN_H

const int PIN_REMOTE_CONTROL = 12;

//MOTORS
const int PIN_WHEEL_RIGHT_FORWARD = 9;
const int PIN_WHEEL_RIGHT_BACKWARD = 8;
const int PIN_WHEEL_LEFT_FORWARD = 7;
const int PIN_WHEEL_LEFT_BACKWARD = 5;
const int PIN_WHEEL_RIGHT_PWM = 6; 
const int PIN_WHEEL_LEFT_PWM = 3;

//CONTROLS
const int PIN_CONTROLLER_DATA = 12;
const int PIN_CONTROLLER_CMD = 11;
const int PIN_CONTROLLER_ATT = 10;
const int PIN_CONTROLLER_CLOCK = 13;

#endif